/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gbe' at '12/05/16 16:56' with Gradle 2.13
 *
 * @author gbe, @date 12/05/16 16:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
